### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by nmilcoff** [Xablu/Xablu.WebApiClient#43]
We want to support talking to GraphQL web services.

The following requirements should be met:
- [x] Install and setup dependency [GraphQL.Client](https://github.com/graphql-dotnet/graphql-client)
- [x] Query builder: We want to support the transformation `object types` => `query string` (more on this later).
- [x] Support query and mutation operations
- [x] Smooth integration with our REST client: Since GraphQL doesn't support uploading files for example, and also because it's very likely that a client app will use a combination of REST + GraphQL, we want to offer both alternatives combined in `WebApiClient`.
- [x] Implement Fusillade priorities for GraphQL calls
- [x] Implement Polly policies for GraphQL calls
- [x] Aliases: Support query aliases through an attribute. Important here is that if an alias is provided, we need to use it inverted (that is the only way it makes sense in our schema). An example is given later on this issue.
- [x] Error handling: We need to make sure we let users know if something went wrong. We can expect a GraphQL error result if something went wrong with the query for example.
- [x] Response handling: Users should receive the information filled in in the model classes they provide for the Query Builder.

## Query builder

We want to implement a solution that most developers recognize as easy to use at a first glance. Our selected approach is similar to how ORMs work in .NET: We require users to define classes for the query types, and use attributes for special things like query parameters.

A transformation example would be something like this:

```c#
public class Author
{
    public string Name { get; set; }

    public List<Book> Books { get; set; }

    [QueryParameter(ExclusiveWith = nameof(Books))]
    public Book Book { get; set; }
}

public class Book
{
    public string Name { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
}
```

The resulting query for the above code should one of these:
1) Query for getting a single book:
```
{
    Author {
        name,
        book(name: "1984") {
            name,
            createdAt
        }
}
```

2) Query for getting the list of books instead:
```
{
    Author {
        name,
        books {
            name,
            createdAt
        }
}
```

In the first query example, the value within parenthesis `name: "1984"` is provided by the developer when building / executing the request. 

### Aliases

Say the GraphQL schema being consumed has a property called `items`. And the user wants to define it as `Products` in the class for the query builder. In that case the `alias` concept from GraphQL can be useful to apply the transformation. The final resulting class should look something like this:

```c#
public class Cart
{ 
    [QueryName("items")]
    public List<Products> Products { get; set; }
}
```

and the resulting query would look like this:

```
{
    Cart {
        products: items {
            ...
        }
}
```

**Comment by LukasThijs** [comment]
Work in progress the tasks seem clear to me.

**Comment by nmilcoff** [comment]
One feature that would be nice to include is sending multiple queries in a single request. 

There are several reasons why one would want to do that, and one of the interesting scenarios is requesting the same query with different IDs ([reference (look for the title "Named Query Results with Aliases")](https://www.howtographql.com/advanced/2-more-graphql-concepts/)). We can discuss whether we include this in the first version or leave it for later in time.

**Comment by nmilcoff** [comment]
Support for GraphQL fragments: Does it add any value to have it? I personally don't think so right now, since using inheritance the same can be achieved. But it's still something we need to decide.
