### ISSUE TITLE
Question about ByteArrayContent

### ISSUE THREAD

**Issue by tematim** [Xablu/Xablu.WebApiClient#6]
Hello,

I have a question about ByteArrayContent with multipart.

I use HttpClient and I can't send this type of content with iOS.

I want to know if your httpClient can send this type without adding value to the body ?

Regards

**Comment by martijn00** [comment]
Do you use the `NSUrlSessionHandler` as `HttpClientHandler` in iOS? We use whatever HttpClient is used when initializing the WebApi.

**Comment by tematim** [comment]
I use a PCL lib with Android and iOS. if I try to use NSUrlSessionHandler in my iOS code, I get errors and can't import using or something to make it work.
Because I can't refer iOS code to my portable lib

Do you have a sample with this handler ?

Regards

**Comment by mvanbeusekom** [comment]
To use the WebApiClient with the NSUrlSessionHandler you simply supply a factory method to the constructor like so:

    var apiClient = new WebApiClient(Settings.ApiBaseUrl, () => new NSUrlSessionHandler()));

If you don't supply a factory method the WebApiClient will use the default managed .NET implementation.

Please note that the NSUrlSessionHandler requires your requests to be send over HTTPS (TLS1.2).

**Comment by tematim** [comment]
Thanks for this tip.

I try, but the type of TContent is not compatible with multipartdatacontent.

Do you know, from my code, the good way to add my two items and the file ?

Regards

**Comment by mvanbeusekom** [comment]
Sorry for the short reply, I am on a small holiday but would still like to help out.

Did you try setting the content-type to "multipart/form-data"?

**Comment by tematim** [comment]
Yes, because my api accept this type.

I try to send it, without filecontent inside the body, because I need to send it like an attachement

**Comment by mvanbeusekom** [comment]
Thanks for the feedback, as mentioned I am currently on a small holiday and don't have access to all my resources. 

I hope you can wait a bit for me to pick this up on Monday. Thanks in advance for your patience.

**Comment by tematim** [comment]
Yes, I can, no problem

**Comment by Kingram91** [comment]
Wonder what his normal holidays are like👨🏾‍💻

**Comment by mvanbeusekom** [comment]
@tematim @Kingram91 my sincere apologies regarding this much overdue reply. And thanks for the wake-up call.

In case you (or someone else) is still interested, to do a multipart form data request using the Xablu.WebApiClient you'll have to implement your custom IHttpContentResolver. This is very trivial and you can find a working (although quick and dirty) example in my personal repo: https://github.com/mvanbeusekom/Sample_WebApiClient_MultiPartFormData
